name: Example Workflow
on: push
jobs:
  example_workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Start Local Validator
        uses: switchboard-xyz/solana-local-validator@v0.1
        with:
          solana-version: v1.14.10
          anchor-version: v0.26.0
          cluster: devnet
          quiet: false
          args:
            "--url https://api.devnet.solana.com  --clone
            2TfB33aLaneQb5TNVwyDz3jSZXS6jdW2ARw1Dgf84XCG --clone
            J4CArpsbrZqu1axqQ4AnrqREs3jwoyA1M5LMiQQmAzB9 --clone
            CKwZcshn4XDvhaWVH9EXnk3iu19t6t5xP2Sy2pD6TRDp --clone
            BYM81n8HvTJuqZU1PmTVcwZ9G8uoji7FKM6EaPkwphPt --clone
            FVLfR6C2ckZhbSwBzZY4CX7YBcddUSge5BNeGQv5eKhy"
      # Local validator will continue to run for any downstream steps
      - name: Test Local Validator
        run: |
          curl -sS http://localhost:8899 -X POST -H 'Content-Type: application/json' -d '{"jsonrpc":"2.0","id":1, "method":"getBlockHeight"}'